import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // tutorialSidebar: [
  //   'simple-world/introduction',
  //   {
  //     type: 'category',
  //     label: 'implementation-creation',
  //     items: [
  //       {
  //         type: 'autogenerated',
  //         dirName: 'simple-world/implementation-creation',
  //       },
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Frontend',
  //     items: [{ type: 'autogenerated', dirName: 'simple-world/frontend' }],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Backend',
  //     items: [{ type: 'autogenerated', dirName: 'simple-world/backend' }],
  //   },
  // ],
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'simple-world' }],
  npmSidebar: [{ type: 'autogenerated', dirName: 'npm' }],
  gitSidebar: [{ type: 'autogenerated', dirName: 'git' }],
};

export default sidebars;
